server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/scooter_rental
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yaml

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    org.example.Senla-task: info

